'\" t
.\"     Title: LATEXILA
.\"    Author: Tanguy Ortolo <tanguy+debian@ortolo.eu>
.\" Generator: DocBook XSL-NS Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/21/2010
.\"    Manual: User commands
.\"    Source: LaTeXila
.\"  Language: English
.\"
.TH "LATEXILA" "1" "11/21/2010" "LaTeXila" "User commands"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
latexila \- Integrated LaTeX Environment for the GNOME desktop
.SH "SYNOPSIS"
.HP \w'\fBlatexila\fR\ 'u
\fBlatexila\fR [\fIOPTIONS\fR] [\fIFILES\fR]
.HP \w'\fBlatexila\fR\ 'u
\fBlatexila\fR {\fB\-h\fR | \fB\-\-help\fR | \fB\-\-help\-all\fR | \fB\-\-help\-gtk\fR}
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBlatexila\fR
command\&.
.PP
LaTeXila
is an Integrated LaTeX Environment for the GNOME desktop\&.
.SH "OPTIONS"
.PP
The program follows the usual GNU command line syntax, with long options starting with two dashes\&. A summary of options is included below\&. For a complete description of options, please use
\fBlatexila \-\-help\fR\&.
.PP
\fB\-n\fR, \fB\-\-new\-document\fR
.RS 4
Create a new document\&.
.RE
.PP
\fB\-\-new\-window\fR
.RS 4
Create a new top\-level window in an existing instance of LaTeXila
.RE
.PP
\fB\-\-display=DISPLAY\fR
.RS 4
X display to use
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show summary of common options\&.
.RE
.PP
\fB\-\-help\-all\fR
.RS 4
Show summary of all options\&.
.RE
.PP
\fB\-\-help\-gtk\fR
.RS 4
Show summary of GTK+ options\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Display version information\&.
.RE
.SH "NOTES"
.PP
By default, when
LaTeXila
is started it reopens the files that were open last time it was used\&. This behaviour can be disabled in the program preferences\&.
.SH "BUGS"
.PP
The upstream
BTS
can be found at
\m[blue]\fBhttp://github\&.com/swilmet/latexila/issues\fR\m[]\&.
.SH "AUTHOR"
.PP
\fBTanguy Ortolo\fR <\&tanguy+debian@ortolo\&.eu\&>
.RS 4
Wrote this manpage for the Debian system\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2010 Tanguy Ortolo
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\&.
.sp
